id: A499DF2D6
title: Prayer to Tsarchen Losal Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:54:57.799565
  last_modified_at: 2022-03-01 01:54:57.799569
