id: A499DF2D6
title: An Aspirational Prayer to Behold the Beautiful Face of Khecharī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:54:57.797840
  last_modified_at: 2022-03-01 01:54:57.797848
